// Generated by Molecule 0.8.0

#define MOLECULEC_VERSION 8000
#define MOLECULE_API_VERSION_MIN 7000

#include "molecule_reader.h"
#include "molecule_builder.h"

#ifndef ARGS_H
#define ARGS_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef MOLECULE_API_DECORATOR
#define __DEFINE_MOLECULE_API_DECORATOR_ARGS
#define MOLECULE_API_DECORATOR
#endif /* MOLECULE_API_DECORATOR */

#undef MOLECULEC_VERSION
#undef MOLECULE_API_VERSION_MIN
#include "blockchain.h"

/*
 * Reader APIs
 */

#define                                 MolReader_ExistingCell_verify(s, c)             mol_verify_fixed_size(s, 12)
#define                                 MolReader_ExistingCell_get_index(s)             mol_slice_by_offset(s, 0, 4)
#define                                 MolReader_ExistingCell_get_source(s)            mol_slice_by_offset(s, 4, 8)
MOLECULE_API_DECORATOR  mol_errno       MolReader_SourceOrBytecode_verify               (const mol_seg_t*, bool);
#define                                 MolReader_SourceOrBytecode_unpack(s)            mol_union_unpack(s)
MOLECULE_API_DECORATOR  mol_errno       MolReader_Input_verify                          (const mol_seg_t*, bool);
#define                                 MolReader_Input_actual_field_count(s)           mol_table_actual_field_count(s)
#define                                 MolReader_Input_has_extra_fields(s)             mol_table_has_extra_fields(s, 2)
#define                                 MolReader_Input_get_source(s)                   mol_table_slice_by_index(s, 0)
#define                                 MolReader_Input_get_args(s)                     mol_table_slice_by_index(s, 1)

/*
 * Builder APIs
 */

#define                                 MolBuilder_ExistingCell_init(b)                 mol_builder_initialize_fixed_size(b, 12)
#define                                 MolBuilder_ExistingCell_set_index(b, p)         mol_builder_set_by_offset(b, 0, p, 4)
#define                                 MolBuilder_ExistingCell_set_source(b, p)        mol_builder_set_by_offset(b, 4, p, 8)
#define                                 MolBuilder_ExistingCell_build(b)                mol_builder_finalize_simple(b)
#define                                 MolBuilder_ExistingCell_clear(b)                mol_builder_discard(b)
#define                                 MolBuilder_SourceOrBytecode_init(b)             mol_union_builder_initialize(b, 8, 0, MolDefault_Bytes, 4)
#define                                 MolBuilder_SourceOrBytecode_set_Bytes(b, p, l)  mol_union_builder_set(b, 0, p, l)
#define                                 MolBuilder_SourceOrBytecode_set_ExistingCell(b, p, l) mol_union_builder_set(b, 1, p, l)
#define                                 MolBuilder_SourceOrBytecode_build(b)            mol_builder_finalize_simple(b)
#define                                 MolBuilder_SourceOrBytecode_clear(b)            mol_builder_discard(b)
#define                                 MolBuilder_Input_init(b)                        mol_table_builder_initialize(b, 128, 2)
#define                                 MolBuilder_Input_set_source(b, p, l)            mol_table_builder_add(b, 0, p, l)
#define                                 MolBuilder_Input_set_args(b, p, l)              mol_table_builder_add(b, 1, p, l)
MOLECULE_API_DECORATOR  mol_seg_res_t   MolBuilder_Input_build                          (mol_builder_t);
#define                                 MolBuilder_Input_clear(b)                       mol_builder_discard(b)

/*
 * Default Value
 */

#define ____ 0x00

MOLECULE_API_DECORATOR const uint8_t MolDefault_ExistingCell[12] =  {
    ____, ____, ____, ____, ____, ____, ____, ____, ____, ____, ____, ____,
};
MOLECULE_API_DECORATOR const uint8_t MolDefault_SourceOrBytecode[8] =  {
    ____, ____, ____, ____, ____, ____, ____, ____,
};
MOLECULE_API_DECORATOR const uint8_t MolDefault_Input[24]        =  {
    0x18, ____, ____, ____, 0x0c, ____, ____, ____, 0x14, ____, ____, ____,
    ____, ____, ____, ____, ____, ____, ____, ____, 0x04, ____, ____, ____,
};

#undef ____

/*
 * Reader Functions
 */

MOLECULE_API_DECORATOR mol_errno MolReader_SourceOrBytecode_verify (const mol_seg_t *input, bool compatible) {
    if (input->size < MOL_NUM_T_SIZE) {
        return MOL_ERR_HEADER;
    }
    mol_num_t item_id = mol_unpack_number(input->ptr);
    mol_seg_t inner;
    inner.ptr = input->ptr + MOL_NUM_T_SIZE;
    inner.size = input->size - MOL_NUM_T_SIZE;
    switch(item_id) {
        case 0:
            return MolReader_Bytes_verify(&inner, compatible);
        case 1:
            return MolReader_ExistingCell_verify(&inner, compatible);
        default:
            return MOL_ERR_UNKNOWN_ITEM;
    }
}
MOLECULE_API_DECORATOR mol_errno MolReader_Input_verify (const mol_seg_t *input, bool compatible) {
    if (input->size < MOL_NUM_T_SIZE) {
        return MOL_ERR_HEADER;
    }
    uint8_t *ptr = input->ptr;
    mol_num_t total_size = mol_unpack_number(ptr);
    if (input->size != total_size) {
        return MOL_ERR_TOTAL_SIZE;
    }
    if (input->size < MOL_NUM_T_SIZE * 2) {
        return MOL_ERR_HEADER;
    }
    ptr += MOL_NUM_T_SIZE;
    mol_num_t offset = mol_unpack_number(ptr);
    if (offset % 4 > 0 || offset < MOL_NUM_T_SIZE*2) {
        return MOL_ERR_OFFSET;
    }
    mol_num_t field_count = offset / 4 - 1;
    if (field_count < 2) {
        return MOL_ERR_FIELD_COUNT;
    } else if (!compatible && field_count > 2) {
        return MOL_ERR_FIELD_COUNT;
    }
    if (input->size < MOL_NUM_T_SIZE*(field_count+1)){
        return MOL_ERR_HEADER;
    }
    mol_num_t offsets[field_count+1];
    offsets[0] = offset;
    for (mol_num_t i=1; i<field_count; i++) {
        ptr += MOL_NUM_T_SIZE;
        offsets[i] = mol_unpack_number(ptr);
        if (offsets[i-1] > offsets[i]) {
            return MOL_ERR_OFFSET;
        }
    }
    if (offsets[field_count-1] > total_size) {
        return MOL_ERR_OFFSET;
    }
    offsets[field_count] = total_size;
        mol_seg_t inner;
        mol_errno errno;
        inner.ptr = input->ptr + offsets[0];
        inner.size = offsets[1] - offsets[0];
        errno = MolReader_SourceOrBytecode_verify(&inner, compatible);
        if (errno != MOL_OK) {
            return MOL_ERR_DATA;
        }
        inner.ptr = input->ptr + offsets[1];
        inner.size = offsets[2] - offsets[1];
        errno = MolReader_BytesVec_verify(&inner, compatible);
        if (errno != MOL_OK) {
            return MOL_ERR_DATA;
        }
    return MOL_OK;
}

/*
 * Builder Functions
 */

MOLECULE_API_DECORATOR mol_seg_res_t MolBuilder_Input_build (mol_builder_t builder) {
    mol_seg_res_t res;
    res.errno = MOL_OK;
    mol_num_t offset = 12;
    mol_num_t len;
    res.seg.size = offset;
    len = builder.number_ptr[1];
    res.seg.size += len == 0 ? 8 : len;
    len = builder.number_ptr[3];
    res.seg.size += len == 0 ? 4 : len;
    res.seg.ptr = (uint8_t*)malloc(res.seg.size);
    uint8_t *dst = res.seg.ptr;
    mol_pack_number(dst, &res.seg.size);
    dst += MOL_NUM_T_SIZE;
    mol_pack_number(dst, &offset);
    dst += MOL_NUM_T_SIZE;
    len = builder.number_ptr[1];
    offset += len == 0 ? 8 : len;
    mol_pack_number(dst, &offset);
    dst += MOL_NUM_T_SIZE;
    len = builder.number_ptr[3];
    offset += len == 0 ? 4 : len;
    uint8_t *src = builder.data_ptr;
    len = builder.number_ptr[1];
    if (len == 0) {
        len = 8;
        memcpy(dst, &MolDefault_SourceOrBytecode, len);
    } else {
        mol_num_t of = builder.number_ptr[0];
        memcpy(dst, src+of, len);
    }
    dst += len;
    len = builder.number_ptr[3];
    if (len == 0) {
        len = 4;
        memcpy(dst, &MolDefault_BytesVec, len);
    } else {
        mol_num_t of = builder.number_ptr[2];
        memcpy(dst, src+of, len);
    }
    dst += len;
    mol_builder_discard(builder);
    return res;
}

#ifdef __DEFINE_MOLECULE_API_DECORATOR_ARGS
#undef MOLECULE_API_DECORATOR
#undef __DEFINE_MOLECULE_API_DECORATOR_ARGS
#endif /* __DEFINE_MOLECULE_API_DECORATOR_ARGS */

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* ARGS_H */
